### ISSUE TITLE
Table name incorrect

### ISSUE THREAD

**Issue by vincentmoulene** [antistatique/drupal-backerymails#5]
The name of `backerymails_sended_mail` should be `backerymails_send_mail`.

Make an update function.

**Comment by tonifisler** [comment]
Should be `backerymail_sent_mails` in a perfect world =)

**Comment by vincentmoulene** [comment]
I suggest `backerymails_sent_mails` because backerymails is the name of the module. ;-) 
Is it better for you @tonifisler?

**Comment by WengerK** [comment]
closed in favor of #18
